name: All_Together

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  file_to_build: all_together.py
  pi_image: raspios_lite_arm64:latest 
  path_to_file: IIoT_Device_Guide_UGA_2023/all_together
  built_file_name: all_together


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
      with: 
        lfs: true
    - name: checkout lfs object
      run: git lfs checkout
    - name: all_together
      uses: pguyot/arm-runner-action@main
      id: all_together
      with:
        image_additional_mb: 3584
        copy_repository_path: /home/pi
        base_image: ${{env.pi_image}}
        commands: |
            sudo apt-get update -y;
            pwd;
            apt-get install -y python3 python3-venv python3-dev python3-pip; 
            cd ${{env.path_to_file}};
            pip3 install requests;
            pip3 install --upgrade pip;
            pip3 install pyinstaller;
            pip3 install mmh3;
            pyinstaller --clean --onefile ${{env.file_to_build}};
            ls -a;
            cd dist;
            ls -a;
            cd ..;
            chmod +x all_together.sh;
            sudo cp /home/pi/IIoT_Device_Guide_UGA_2023/all_together/all_together_initialize.service /lib/systemd/system/all_together_initialize.service;
            sudo chmod 644 /lib/systemd/system/all_together_initialize.service;
            sudo systemctl enable all_together_initialize.service;
    - name: Compress the release image 
      run: |
        sudo xz -T 0 -v ${{ steps.all_together.outputs.image }}
    - name: Upload the image artifact
      uses: actions/upload-artifact@v3 #uploads the image
      with:
        name: build_image
        path: ${{ steps.all_together.outputs.image }}.xz
        if-no-files-found: error
        retention-days: 10

            #         sudo cp /home/pi/IIoT_Device_Guide_UGA_2023/all_together/all_together.service /lib/systemd/system/all_together.service;
            # sudo chmod 644 /lib/systemd/system/all_together.service;
            # sudo systemctl enable all_together.service;

