name: hello

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo #checkout code so most up-to-date version is accessible to the runner
      uses: actions/checkout@main
      with: 
        lfs: true #lfs is github large file storage system
    - name: checkout lfs object
      run: git lfs checkout 
    - name: Build test
      uses: pguyot/arm-runner-action@main #this action emulates an ARM CPU and a desired operating system $pi_image
      id: create crontab
      with:
        image_additional_mb: 3584
        copy_repository_path: /home/pi
        base_image: ${{env.pi_image}}
        commands: |
          chmod +x launcher.sh
          echo "@reboot sh /home/pi/launcher.sh >/home/pi/logs/cronlog 2>&1" | crontab -


